### ISSUE TITLE
Pypi update to incorporate work in 2020

### ISSUE THREAD

**Issue by robmoore** [zero323/pyspark-asyncactions#16]
Just curious if you are thinking of updating this package in Pypi? I ask because there were some commits in the earlier part of this year that would be helpful (in particular, the ability to set `spark.driver.cores` was fixed).

**Comment by zero323** [comment]
I didn't plan to, but it is not a problem, if it helps.

**Comment by zero323** [comment]
Added https://pypi.org/project/pyspark-asyncactions/0.0.3/

Please let me know if you have any question or experience any problems.

**Comment by robmoore** [comment]
Thanks! I appreciate the quick response.
